# Generated by Django 4.2.30 on 2026-06-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apiusagelog",
            new_name="api_managem_api_key_335076_idx",
            old_name="api_managem_api_key_9039e5_idx",
        ),
    ]
