# Generated by Django 4.2.30 on 2026-06-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ml_engine", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="anomalyflag",
            new_name="ml_anomaly__symbol_bbd6dd_idx",
            old_name="ml_anomaly__symbol_1e7852_idx",
        ),
    ]
