services:
  postgres:
    image: postgres:15-alpine
    container_name: b100_postgres_fresh
    restart: unless-stopped
    environment:
      POSTGRES_DB: bluestock_dw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b100pass
    ports:
      - "5432:5432"
    volumes:
      - b100_fresh_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: b100_redis_fresh
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  b100_fresh_pgdata:
